# Generated by Django 3.1 on 2020-10-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_app', '0003_auto_20201023_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
