# Generated by Django 3.1 on 2020-10-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_app', '0004_auto_20201023_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('gm', 'Gram')], default=None, max_length=100, null=True),
        ),
    ]
