# Generated by Django 3.1 on 2020-10-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    
    dependencies = [
        ('ks_app', '0007_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Order',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('gm', 'Gram'), ('lt', 'Litre')], default=None, max_length=100, null=True),
        ),
    ]
