# Generated by Django 3.1 on 2020-11-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_app', '0008_auto_20201027_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.BigIntegerField(default=None, max_length=10, null=True),
        ),
    ]
