# Generated by Django 3.1 on 2020-11-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_app', '0009_auto_20201101_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
