# Generated by Django 3.1 on 2020-11-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_app', '0010_auto_20201102_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='pics'),
        ),
    ]
