# Generated by Django 5.2.7 on 2026-01-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_app', '0012_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
